api/urls.py
# -*- coding: utf-8 -*-
from django.urls import re_path, path
from django.conf.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#from api.views import APICuotasViewSet,APIBoletasViewSet
from api.views import CuotasListView,BoletasListView
# from rest_framework_jwt.views import obtain_jwt_token,refresh_jwt_token,verify_jwt_token
from rest_framework import routers
from rest_framework import permissions
from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title=u'Documentación de la Web API.')

router = routers.DefaultRouter()
# router.register(r'cuotas', APICuotasViewSet)
#router.register(r'boletas', APIBoletasViewSet)

app_name = 'api'
urlpatterns = [       
   path('', include(router.urls)),
   # url(r'^token/', obtain_jwt_token, name='token_create'),    
   # url(r'^token-refresh/', refresh_jwt_token,name='token_refresh'),
   # url(r'^token-verify/', verify_jwt_token,name='token_verify'),

   path('cuotas/', CuotasListView.as_view(),name="api_cuotas"),
   path('boletas/',BoletasListView.as_view(),name="api_boletas"),
   #url(r'^padrones/(?P<idResp>[^/]+)/$', APIPadronesList.as_view(),name="api_padrones"),    

   

   # url(r'^cuota/(?P<idc>[^/]+)/$', APICuota.as_view(),name="api_cuota_ver"),

   path('', schema_view),
   path('auth/', include('rest_framework.urls')),   

]

tadese/urls.py
# -*- coding: utf-8 -*-
from django.urls import re_path, path
from django.conf import settings
import os
from .views import *
from tasasweb.views import volverHome
from django.views.generic import RedirectView,TemplateView

# Uncomment the next two lines to enable the admin:
app_name = 'tadese'

urlpatterns = [    
    re_path(r'^$', volverHome,name="inicio"),
    re_path(r'^municipio/$', verDDJJDrei,name="municipio"),
    re_path(r'^estudios/$', EstudiosView.as_view(),name="padrones_estudio"),
    re_path(r'^padrones/$', PadronesView.as_view(),name="padrones_responsable"),
    
    re_path(r'^cuotas/(?P<idp>[^/]+)/$', BusquedaCuotasView.as_view(),name="ver_cuotas"),
    re_path(r'^cuotas/(?P<idp>[^/]+)/(?P<anio>\d+)/$', BusquedaCuotasView.as_view(),name="buscarCuotasAP"),

    re_path(r'^drei/(?P<idc>\d+)/$', DreiLiquidarCreateView.as_view(),name="drei_liquidarBoleta"),
    re_path(r'^drei2/(?P<idb>\d+)/$', DreiLiquidarUpdateView.as_view(),name="drei_reliquidarBoleta"),
    re_path(r'^drei3/(?P<idb>\d+)/$', DreiRectificar.as_view(),name="drei_rectificarBoleta"),
    re_path(r'^drei4/(?P<idc>\d+)/$', DreiRectificarNew.as_view(),name="drei_rectificarNewBoleta"),

    re_path(r'^drei/eliminar/(?P<idb>[^/]+)/$', EliminarBoleta,name="eliminar_boleta"),
    re_path(r'^drei/modif_bases/(?P<idb>\d+)/$', DreiModifBasesView.as_view(),name="drei_modif_bases"),
    
    re_path(r'^punitorios/(?P<idc>\d+)/(?P<valor>\d+\.\d+)/$',calcularPunitoriosForm,name="calcularPunitorios"),
    re_path(r'^punitoriosLiq/$',generarPunitoriosLiq,name="generarPunitoriosLiq"),

    re_path(r'^imprimir/(?P<idc>\d+)/$',imprimirPDF,name="imprimirPDF"),
    re_path(r'^imprimir/(?P<idc>\d+)/(?P<idb>\d+)/$',imprimirPDF,name="imprimirPDFBoleta"),
    re_path(r'^imprimirLiqWeb/(?P<id_liquidacion>\d+)/$',imprimirPDFLiqWeb,name="imprimirPDFLiqWeb"),
    
    re_path(r'^drei/ddjja/(?P<idp>\d+)/$', DreiDDJJAList.as_view(),name="drei_ddjja_list"),
    re_path(r'^drei/ddjja/(?P<idp>\d+)/(?P<anio>\d+)/$', DreiDDJJAList.as_view(),name="drei_ddjja_list"),

    re_path(r'^estudios/editar/(?P<pk>\d+)$', EstudiosUpdateView.as_view(), name='estudio_editar'),
    
    re_path(r'^liquidacion/(?P<idp>\d+)/$', generarLiquidacion,name="generarLiquidacion"),
    
    re_path(r'^estudios/passwd/(?P<usrEstudio>.+)$', mandarEmailEstudio, name='mandarEmailEstudio'),

    re_path(r'^suscripcion/alta/(?P<idp>\d+)/$', suscripcion_alta,name="suscripcion_alta"),
    re_path(r'^suscripcion/baja/(?P<idp>\d+)/$', suscripcion_baja,name="suscripcion_baja"),    

    re_path(r'^pago/$', generarPago,name="pago"),

    re_path(r'^pago/exito/$', generarPagoExito,name="pago_exito"),
    re_path(r'^pago/error/(?P<idp>\d+)/$', generarPagoError,name="pago_error"),

   
    ]

tasasweb/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include
from django.urls import re_path, path
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

from .views import login,logout,handler404,handler500

urlpatterns = [    
    path('', include('tadese.urls')),    
    path('api/v1/', include('api.urls')),
    path('login/', login,name="login"),
    path('logout/', logout,name="logout"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:    
	import debug_toolbar
	urlpatterns += re_path(r'^__debug__/', include(debug_toolbar.urls)),
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
handler500 = handler500
handler404 = handler404

templates/base.html
<!DOCTYPE HTML>
<html>

<head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge" charset="utf-8">
        {% load static from staticfiles %}
        <title>{% block title %}Sistema de Liquidación de Boletas OnLine{% endblock %}</title>
        <META NAME="Description" CONTENT="{% block description %}Sistema de Boletas WEB{% endblock %}">
        <link rel="shortcut icon" href="{% static 'images/logo.png' %}"  type="image/png">
        
        <link href="http://fonts.googleapis.com/css?family=Carme" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Gafata" rel="stylesheet" type="text/css">

        <link rel="stylesheet" href="{% static 'css/base.css'%}?{% now "Ymd"%}" type="text/css" >
        
        <link rel="stylesheet" href="{% static 'css/table.css'%}?{% now "Ymd"%}" type="text/css" />
        <link rel="stylesheet" href="{% static 'css/modals.css'%}?{% now "Ymd"%}" type="text/css" />
        <link rel="stylesheet" href="{% static 'alertifyjs/css/alertify.css' %}" type="text/css" />
        <link rel="stylesheet" href="{% static 'alertifyjs/css/themes/bootstrap.css' %}" type="text/css" />
        <link rel="stylesheet" href="{% static 'bootstrap/css/jquery-ui.css' %}" type="text/css" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <link href="{% static 'css/colorbox.css' %}" rel="stylesheet" type="text/css">

        <link rel="stylesheet" href="{% static 'DataTables/datatables.css' %}" type="text/css" />        
        <link rel="stylesheet" href="{% static 'DataTables/DataTables-1.10.15/css/dataTables.bootstrap.min.css' %}" type="text/css" />        
        <link rel="stylesheet" href="{% static 'DataTables/Buttons-1.5.1/css/buttons.bootstrap.min.css' %}" type="text/css" />
        <link rel="stylesheet" href="{% static 'DataTables/FixedHeader-3.1.2/css/fixedHeader.bootstrap.min.css' %}" type="text/css" />
        <link rel="stylesheet" href="{% static 'DataTables/FixedHeader-3.1.2/css/fixedHeader.dataTables.min.css' %}" type="text/css" />
        <link rel="stylesheet" href="{% static 'DataTables/Buttons-1.5.1/css/buttons.dataTables.min.css' %}" type="text/css" />
        <link rel="stylesheet" href="{% static 'DataTables/Buttons-1.5.1/css/buttons.bootstrap.min.css' %}" type="text/css" />
    	  <link rel="stylesheet" href="{% static 'css/estilo.css'%}?{% now "Ymd"%}" type="text/css" />
        {% block extra_css %}
    	{% endblock %}

        <script src="{% static 'bootstrap/js/html5shiv.js' %}" type="text/javascript"></script>
        <script src="{% static 'bootstrap/js/respond.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'bootstrap/js/jquery.js' %}" type="text/javascript" ></script>
        <script src="{% static 'bootstrap/js/jquery-ui.js' %}" type="text/javascript" ></script>
        <script src="{% static 'js/libs/bootstrap.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'bootstrap/js/sorttable.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/filtros.js' %}" type="text/javascript"></script>        
        <script src="{% static 'alertifyjs/alertify.js' %}" type="text/javascript"></script>
        <script type="text/javascript" src="{% static 'js/jquery.colorbox-min.js' %}"></script>

        {% block exxtra_js %}
          <script src="{% static 'DataTables/moment.min.js' %}" type="text/javascript"></script>      
          <script src="{% static 'DataTables/datatables.js' %}" type="text/javascript"></script>            
          <script src="{% static 'DataTables/datetime-moment.js' %}" type="text/javascript"></script>                  
          <script src="{% static 'DataTables/Responsive-2.2.1/js/dataTables.responsive.min.js' %}" type="text/javascript"></script>
          <script src="{% static 'DataTables/Responsive-2.2.1/js/responsive.bootstrap.min.js' %}" type="text/javascript"></script>
          <script src="{% static 'DataTables/Buttons-1.5.1/js/dataTables.buttons.min.js' %}" type="text/javascript"></script>
          <script src="{% static 'DataTables/Buttons-1.5.1/js/buttons.colVis.min.js' %}" type="text/javascript"></script>
          <script src="{% static 'DataTables/Buttons-1.5.1/js/buttons.bootstrap.min.js' %}" type="text/javascript"></script>
          <script src="{% static 'DataTables/FixedHeader-3.1.3/js/dataTables.fixedHeader.min.js' %}" type="text/javascript"></script>    
        {% endblock %}
        {% block extra_js %}
        {% endblock %}
        
<script>
   $(document).ready(function(){
        $("#codigoInternet").colorbox({inline:true, width:"650"});             
        $('[data-toggle=tooltip]').tooltip();
        $('#modal_cartel').modal('show');
    });
    alertify.defaults.transition = "slide";
    alertify.defaults.theme.ok = "btn btn-primary";
    alertify.defaults.theme.cancel = "btn btn-default";
    alertify.defaults.theme.input = "form-control";  
</script>
</head>

<body>

    {% if user.is_authenticated %}
      <div class="container2">    
          <div class="row">
            {% include "header.html" %}
          </div>
    {% else %} 
    <div class="container">          
    {% endif %}         
      {% block principal %}          
      {% endblock principal %}
    </div>
    
</body>

</html>

templates/buscador.html
{% if padron %}
<br>
<ul class="list-group">
    <a  class="list-group-item active"><b>Buscar Cuotas por Padrón/Año</b></a>

    <li class="list-group-item">
         <div class="btn-group">
                <button id="idp" value="{{ padron.id_padron }}" type="button" class="btn btn-principal btn-primary dropdown-toggle btn-xs" data-toggle="dropdown">
                    {{ padron.padron }} ({{ padron.tributo__abreviatura }}) <b class="caret"></b>
                </button>
              <ul id="menuidp" class="dropdown-menu filtros" role="menu">
                {% for idp in padr %}
                    <li><a val="{{ idp.id_padron }}">{{ idp.padron }} ({{ idp.tributo__abreviatura }})</a></li>
                {% endfor %}
              </ul>
            </div>
     
        <div class="btn-group pull-right">
                 <button id="anio" value="0" type="button" class="btn btn-principal btn-primary dropdown-toggle btn-xs" data-toggle="dropdown" title="Filtrar por Padrón">
                   {% if not anio %}
                     Todos
                    {% else %}
                    {{anio}}
                    {% endif %}
                    <b class="caret"></b>
                </button>
              {% include "anios.html" %}
            </div>
    </li>
    
</ul>
{% endif %}

templates/header.html
{% load static from staticfiles %}
<header>
	<nav class="navbar navbar-default navbar-inverse" role="navigation">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<a class="navbar-brand" href="http://www.grupoguadalupe.com.ar"  >
				<img class="logoGG" alt="20x20" src="{% static 'images/GG.png' %}" title="Ir a la Página de Grupo Guadalupe Sistemas" />
			</a>				
			
        </div>
			<ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li ><a href="/"><i class="glyphicon glyphicon-home"> </i><span> Inicio</span></a></li>
                    {% if user.is_superuser %}
                        <li class="divider-vertical"></li>
                        <li><a href="/admin/"><i class="glyphicon glyphicon-wrench"> </i><span> Administrar</span></a></li>
                    {% endif %}

                    <li class="divider-vertical"></li>
                {% endif %}
                {% include "menues.html" %}
			</ul>
		
	</nav>
</header>

templates/index.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block extra_js %}
		<script src="{% static 'js/selectTributo.js' %}" type="text/javascript" ></script>
{% endblock %}


{% block principal %}	
	 {% if user.is_authenticated %}
          <div class="row fondo-row">
                <div class="col-xs-3 col-lg-2">            
	                {% include "logoMuni.html" %}            
	                
	                {% block menuizq %}
	                {% endblock menuizq%}
	                
	                {% include "observaciones.html" %}
                </div>

                <div class="col-xs-9 col-lg-10 mas-izq">
	                {% block main %}
	                {% endblock main%}
                </div>
          </div>                   

          
	 {% else %}
	 	{% include "login.html" %}
	 {% endif %}
		

<script>
$(document).ready(function(){ 
	$("#email").click(function(){
    	var $usr = $("input[name='username']").val();
    	if ($usr == '')
	           	{alertify.alert('ATENCIÓN','El usuario/email no es válido!');    }
	    else{  
    	$.ajax({
	        url: "/estudios/passwd/"+$usr,
	        type: "get", // or "get"       
	        success: function(data) {
	              alertify.alert('ATENCIÓN',data);  
        }});}    
     });
 
});
</script>
{% include "modales.html" %}
{% endblock principal %}


		

templates/logoMuni.html
{% load static from staticfiles %}
<a href="{{sitio.link_retorno}}"> <img title="Volver a la Página del Municipio" src="{% static 'munis/' %}{{dirMuni}}/logo.png?{% now "Ymd"%}" alt="InfoMunicipio" class="img-thumbnail logo_muni" ></a>

templates/modales.html
{% load static from staticfiles %}


<!-- Modal -->
<div style="display:none">
<div id="modal_codigo" tabindex="-1" role="dialog" aria-labelledby="lblmodal_codigo" aria-hidden="true">
<div class="cboxPhoto">
       <img class="" src="{% static 'images/codigointernet.png' %}" alt="codigoInternet" /> 
       <p>{{sitio.detalleContrib}} </p>
</div><!-- /.modal -->
</div><!-- /.modal -->
</div>

templates/observaciones.html
<br>
<ul class="list-group ">   
    <a  class="list-group-item active"><b>Información Adicional</b></a>
   {% if sitio.linea1 %}
    <li class="list-group-item formularios"><i>{{sitio.linea1}}</i>
    </li>
   {% endif %}
   {% if sitio.linea2 %}
    <li class="list-group-item formularios"><i>{{sitio.linea2}}</i>
    </li>
   {% endif %}

</ul>

<ul class="list-group formularios">
    <a  class="list-group-item" target="_blank" href="{{DIR_MUNIS}}munis/{% if estudio %}manualEC.pdf{% else %}manualCP.pdf{% endif %}">
    <b>Descargar Instructivo <i class="glyphicon glyphicon-cloud-download pull-right"> </i></b></a>
</ul>

<ul class="list-group formularios">
    <a  class="list-group-item active botonesLogin" href="#modal_codigo" id="codigoInternet" role="button"><b>¿Cómo obtener el Código? <i class="glyphicon glyphicon-question-sign pull-right"></i></b></a>
</ul>

templates/padrones_estudio.html
{% extends "index.html" %}

{% block menuizq %}
<br>
<ul class="list-group">
    <a  class="list-group-item active"><b>Estudio Contable</b></a>
    <li class="list-group-item"><b>{{estudio.pk}} - {{estudio.denominacion}}</b></li>
{% if padr %}
    <li class="list-group-item">  Padrones Encontrados <span class="badge">{{padr|length}}</span></li>
{% endif %}
    {% block canCuotas %}
    {% endblock canCuotas %}
</ul>

{% endblock menuizq %}


{% block main %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong>{{ message }}</strong>
                
            </div>
        {% endfor %}
    {% endif %}
    <div class="barra_titulo">
            <b>Listado Completo de Padrones DReI a cargo del Estudio {{estudio.denominacion}}</b>    
    </div>
    <div class="datagrid col-md-12 mas-izq mas-der">
    <table id="tablaPadrones" class="table compact table-no-bordered table-hover table-striped tabla_nueva nowrap ">    
    <thead>
        <tr class="info">
            <th class="imprimir text-center" data-priority="4">Nº Padrón/Partida</th>            
            <th class="imprimir text-left">Responsable</th>            
            <th class="imprimir text-center">Total Cuotas</th>
            <th class="no-sort text-center" >Ver Cuotas</th>            
        </tr>
    </thead>
    <tbody>
        {% for item in padr %}
        <tr>
            <td class="text-center"><span class="label label-primary">{{ item.padron }}</span></td>            
            <td title="{{ item.nombreResp}}" class="text-left">{{ item.nombreResp|truncatechars:60 }}</td>
            <td>{{ item.cant_cuotas }} cuotas.</td>
            <td><a  href="{% url 'tadese:ver_cuotas' item.id_padron %}" title="Ver Cuotas del Padrón {{item.padron}}"><span class="glyphicon glyphicon-search iconosTabla"></span> </a>
            {% if user.is_superuser %} 
                    <a  href="{% url 'tadese:drei_ddjja_list' item.id_padron %}" title="DDJJ Anual del Padrón {{item.padron}}"><span class="glyphicon glyphicon-list-alt iconosTabla"></span> </a>
            {% endif %}
             </td> 
            
        </tr>
        {% endfor %}

    </tbody>
   
    </table>
    </div>

<script type="text/javascript">

    $(document).ready(function() { 

                moment.locale('es');
                $.fn.dataTable.moment('DD/MM/YYYY'); 
                var tabla = $('#tablaPadrones').DataTable({
                            "language": {
                                "decimal": ",",
                                "thousands": ".",                
                                "sProcessing": "Procesando...",
                                "sLengthMenu": "Mostrar _MENU_ registros",
                                "sZeroRecords": "No se encontraron resultados",
                                "sEmptyTable": "No hay registros en esta tabla",
                                "sInfo": " _TOTAL_ padrones encontrados.",
                                "sInfoEmpty": "No existen padrones para el período seleccionado",
                                "sInfoFiltered": "(de un total de _MAX_ padrones)",
                                "sInfoPostFix": "",
                                "sSearch": "Buscar Padrón/Representante:",
                                "sUrl": "",
                                "sInfoThousands": ".",
                                "sLoadingRecords": "Cargando...",
                                "oPaginate": {
                                    "sFirst": "Primero",
                                    "sLast": "Último",
                                    "sNext": "Siguiente",
                                    "sPrevious": "Anterior"
                                },
                                "oAria": {
                                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                                },
                                      
                            },                      
                            "columnDefs": [ {
                                  "targets"  : 'no-sort',
                                  "orderable": false,
                                }],          
                           "scrollY":        '65vh',
                           "scrollCollapse": false,
                           "paging":   false,
                           "lengthMenu": [[20, 50, -1], [20, 50, "Todos"]],
                           "autoWidth": true,           
                           "order": [],
                           "colReorder": true,
                           "searching": true,
                            "responsive": true,
                            // dom: 'frtlip',
                            // "dom": '<"top"i>rt<"pie"lp><"clear">',
                             // "dom": '<"datatable_top"lf<t>"pie"ip>',
                             "dom": "<'col-sm-12' <'row fondo_busqueda'<'col-sm-12'f>><'row'<tr>>>",
                           
                           
                        });
                });
    </script>                
{% endblock main %}

templates/padrones_representante.html
{% extends "index.html" %}

{% block menuizq %}
{% include "buscador.html" %}   
{% endblock menuizq %}


{% block main %}

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong>{{ message }}</strong>
                
            </div>
        {% endfor %}
    {% endif %}
    <div class="barra_titulo">
            <b>Listado Completo de Padrones de {{user.first_name}}</b> 
    </div>
    <div class="datagrid col-md-12 mas-izq mas-der">
    <table id="tablaPadrones" class="table compact table-no-bordered table-hover table-striped tabla_nueva nowrap ">
    <thead>
        <tr class="info">
            <!-- <th>Id</th> -->            
            <th class="imprimir text-center" data-priority="4">Nº Padrón/Partida</th>
            <th class="imprimir text-center" data-priority="4">Tributo</th>
            <th class="imprimir text-center" data-priority="4">Total Cuotas</th>
            <th class="no-sort text-center" data-priority="4">Ver Cuotas</th>           
        </tr>
    </thead>
    <tbody>
        {% for item in padr %}
        <tr>
        <!-- <td>{{ item.id_padron }}</td> -->
        <td><span class="label label-primary">{{ item.padron }}</span></td>
        <td>
            {% if item.tributo == 5 %}
                    {{ item.tributo__descripcion }} ({{ item.tributo__abreviatura }}) (Nº:{{item.id_padron}})
            {% else %}
                {{ item.tributo__descripcion }} ({{ item.tributo__abreviatura }})
            {% endif %}        
        </td>
        <td>{{ item.id_padron__count }} cuotas.</td>
        <td><a  href="{% url 'tadese:ver_cuotas' item.id_padron %}" title="Ver Cuotas del Padrón {{item.padron}}"><span class="glyphicon glyphicon-search iconosTabla"></span> </a>
        {% if item.tributo == 6 %}
           {#  <a  href="{% url 'drei_ddjja_list' item.id_padron %}" title="DDJJ Anual del Padrón {{item.padron}}"><span class="glyphicon glyphicon-list-alt iconosTabla"></span> </a> #}
         {% endif %}   
        </td>
        </tr>        
        {% endfor %}        
    </tbody>
    <tfoot>
        <tr>
            <th></th>
            <th></th>                            
            <th></th>
            <th ></th>            
        </tr>
    </tfoot>
    </table>
    </div>               

<script type="text/javascript">

    $(document).ready(function() { 

                moment.locale('es');
                $.fn.dataTable.moment('DD/MM/YYYY'); 
                var tabla = $('#tablaPadrones').DataTable({
                            "language": {
                                "decimal": ",",
                                "thousands": ".",                
                                "sProcessing": "Procesando...",
                                "sLengthMenu": "Mostrar _MENU_ registros",
                                "sZeroRecords": "No se encontraron resultados",
                                "sEmptyTable": "No hay registros en esta tabla",
                                "sInfo": " _TOTAL_ padrones encontrados.",
                                "sInfoEmpty": "No existen padrones para el período seleccionado",
                                "sInfoFiltered": "(de un total de _MAX_ padrones)",
                                "sInfoPostFix": "",
                                "sSearch": "Buscar Padrón/Tributo:",
                                "sUrl": "",
                                "sInfoThousands": ".",
                                "sLoadingRecords": "Cargando...",
                                "oPaginate": {
                                    "sFirst": "Primero",
                                    "sLast": "Último",
                                    "sNext": "Siguiente",
                                    "sPrevious": "Anterior"
                                },
                                "oAria": {
                                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                                },
                                      
                            },                      
                            "columnDefs": [ {
                                  "targets"  : 'no-sort',
                                  "orderable": false,
                                }],          
                           "scrollY":        '65vh',
                           "scrollCollapse": false,
                           "paging":   false,
                           "lengthMenu": [[20, 50, -1], [20, 50, "Todos"]],
                           "autoWidth": true,           
                           "order": [],
                           "colReorder": true,
                           "searching": true,
                            "responsive": true,
                            // dom: 'frtlip',
                            // "dom": '<"top"i>rt<"pie"lp><"clear">',
                             // "dom": '<"datatable_top"lf<t>"pie"ip>',
                             "dom": "<'col-sm-12' <'row fondo_busqueda'<'col-sm-4'f><'col-sm-8'i>><'row'<tr>>>",
                           
                           
                        });
                });
    </script>
{% endblock main %}

templates/suscripcion.html
<br>
<ul class="list-group">
    <a  class="list-group-item active"><b>Suscripción Boleta Digital</b>
        {% if suscripcion_msj %}
            <i class="glyphicon glyphicon-question-sign pull-right" title="{{suscripcion_msj}}"></i>
        {% endif %}
    </a>
    {% if suscriptor %}
        {% if suscriptor.activa %}
            <li class="list-group-item center-block">Fecha Alta <span class="badge badge-info">{{suscriptor.fecha_alta|date:"d/m/Y"}}</span></li>
            <li class="list-group-item text-center">
                <button id="desuscribir" type="button" class="btn btn-danger btn-xs"><i class="fa fa-thumbs-down"></i> Desuscribirme</button>
            </li>
        {% else %}
            <li class="list-group-item text-center">
                <button id="suscribir" type="button" class="btn btn-primary btn-xs"><i class="fa fa-thumbs-up"></i> Suscribirme</button>
            </li>
        {% endif %}
    {% else %}
        <li class="list-group-item text-center">
            <button id="suscribir" type="button" class="btn btn-primary btn-xs"><i class="fa fa-thumbs-up"></i> Suscribirme</button>
        </li>
    {% endif %}
</ul>